# get all properties used for authority control (ISSN, IMDb ID, LCCN, GND...)
SELECT ?prop ?label WHERE {
  ?prop wdt:P31/wdt:P279* wd:Q18614948 .
  ?prop rdfs:label ?label . FILTER(LANG(?label)="en")
}
