package de.gwdg.metadataqa.wikidata;

public enum Command {
  TRANSFORMATION,
  READ,
  ENTITY_RESOLUTION,
  ENTITY_RESOLUTION_FROM_LIST,
  ENTITY_CLASS_RESOLUTION,
  ENTITY_CLASS_RESOLUTION_MULTITHREAD,
  EXTRACT_LABELS_FROM_FILE;
}
